name: finch_doc
description: An example web application with finch package dart.
version: 3.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_web_compilers: 
  test:
  dart_dev: 
  build_runner:
  json_serializable:

dependencies:
  finch: 1.0.0
    # path: ../dart/dweb
  markdown: ^7.3.0
  watcher: 1.1.4
  